version: '3.8'

services:

  mysqldb-container:
    image: mysql:8
    container_name: mysqldb-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  springapp:
    image: narasimha1247/narasimha
    container_name: springapp
    depends_on:
      mysqldb-container:
        condition: service_healthy
    ports:
      - "8080:8080"
