services:
  application:
    image: narasimha1247/narasimha
    container_name: spring-container
    ports:
      - "8080:8080"
    networks:
      - docker-mysql
    depends_on:
      mysqldb:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10

  mysqldb:
    image: mysql:8.0
    container_name: mysqldb-container
    ports:
      - "3306:3306"
    networks:
      - docker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  docker-mysql:
